import {
  X,
  XCircle,
  Eye,
  EyeOff,
  CheckCircle,
  AlertCircle,
  ChevronDown,
  ChevronLeft,
  ChevronsLeft,
  PlusCircle,
  MinusCircle,
  Calendar,
  Clock,
  LogOut,
  Menu,
  LayoutDashboard,
  LayoutGrid,
  List,
  UtensilsCrossed,
  ClipboardList,
  Gift,
  Settings,
  Palette,
  Pencil,
  Trash2,
  Plus,
  Minus,
  Check,
  MapPin,
  Bike,
  CreditCard,
  Banknote,
  Smartphone,
  MessageCircle,
  Users,
  Image as ImageIcon,
  GripVertical,
  Sun,
  Moon,
  CircleHelp,
  ChevronRight,
  Archive,
  ArchiveRestore,
  Send,
  Ban,
  Maximize,
  Minimize,
  ShoppingCart,
  Search,
  Puzzle,
  QrCode,
  ChefHat,
  Table2,
  FileText,
  Sparkles,
  Hash,
  Copy,
  EllipsisVertical,
  LockOpen,
  ExternalLink,
  CalendarCheck,
  GraduationCap,
  Package,
  Briefcase,
  ArrowLeftRight,
  BellRing,
} from 'lucide-vue-next'

export const iconRegistry = {
  // internal lib icons
  crossRound: XCircle,
  eye: Eye,
  eyeClose: EyeOff,
  warningRound: AlertCircle,
  checkRound: CheckCircle,
  chevronRound: ChevronDown,
  chevronLeft: ChevronLeft,
  collapse: ChevronsLeft,
  plusRound: PlusCircle,
  minusRound: MinusCircle,
  calendar: Calendar,
  close: X,
  // app icons
  logOut: LogOut,
  menu: Menu,
  dashboard: LayoutDashboard,
  dishes: UtensilsCrossed,
  orders: ClipboardList,
  promotions: Gift,
  settings: Settings,
  pencil: Pencil,
  trash: Trash2,
  plus: Plus,
  minus: Minus,
  check: Check,
  mapPin: MapPin,
  bike: Bike,
  creditCard: CreditCard,
  banknote: Banknote,
  smartphone: Smartphone,
  messageCircle: MessageCircle,
  clock: Clock,
  palette: Palette,
  users: Users,
  image: ImageIcon,
  grip: GripVertical,
  layoutGrid: LayoutGrid,
  list: List,
  sun: Sun,
  moon: Moon,
  help: CircleHelp,
  chevronRight: ChevronRight,
  archive: Archive,
  archiveRestore: ArchiveRestore,
  send: Send,
  ban: Ban,
  maximize: Maximize,
  minimize: Minimize,
  cart: ShoppingCart,
  search: Search,
  puzzle: Puzzle,
  qrCode: QrCode,
  chefHat: ChefHat,
  tableIcon: Table2,
  fileText: FileText,
  sparkles: Sparkles,
  hash: Hash,
  copy: Copy,
  moreVertical: EllipsisVertical,
  unlock: LockOpen,
  externalLink: ExternalLink,
  calendarCheck: CalendarCheck,
  graduationCap: GraduationCap,
  package: Package,
  briefcase: Briefcase,
  swap: ArrowLeftRight,
  bellRing: BellRing,
} as const

export type IconName = keyof typeof iconRegistry
