import {
  X,
  XCircle,
  Eye,
  EyeOff,
  CheckCircle,
  AlertCircle,
  ChevronDown,
  ChevronsLeft,
  PlusCircle,
  MinusCircle,
  Calendar,
  Clock,
  LogOut,
  Menu,
  LayoutDashboard,
  LayoutGrid,
  List,
  UtensilsCrossed,
  ClipboardList,
  Gift,
  Settings,
  Palette,
  Pencil,
  Trash2,
  Plus,
  Check,
  MapPin,
  Bike,
  CreditCard,
  Banknote,
  Smartphone,
  MessageCircle,
  Users,
  Image as ImageIcon,
  GripVertical,
  Sun,
  Moon,
  CircleHelp,
  ChevronRight,
  Archive,
  ArchiveRestore,
} from 'lucide-vue-next'

export const iconRegistry = {
  // internal lib icons
  crossRound: XCircle,
  eye: Eye,
  eyeClose: EyeOff,
  warningRound: AlertCircle,
  checkRound: CheckCircle,
  chevronRound: ChevronDown,
  collapse: ChevronsLeft,
  plusRound: PlusCircle,
  minusRound: MinusCircle,
  calendar: Calendar,
  close: X,
  // app icons
  logOut: LogOut,
  menu: Menu,
  dashboard: LayoutDashboard,
  dishes: UtensilsCrossed,
  orders: ClipboardList,
  promotions: Gift,
  settings: Settings,
  pencil: Pencil,
  trash: Trash2,
  plus: Plus,
  check: Check,
  mapPin: MapPin,
  bike: Bike,
  creditCard: CreditCard,
  banknote: Banknote,
  smartphone: Smartphone,
  messageCircle: MessageCircle,
  clock: Clock,
  palette: Palette,
  users: Users,
  image: ImageIcon,
  grip: GripVertical,
  layoutGrid: LayoutGrid,
  list: List,
  sun: Sun,
  moon: Moon,
  help: CircleHelp,
  chevronRight: ChevronRight,
  archive: Archive,
  archiveRestore: ArchiveRestore,
} as const

export type IconName = keyof typeof iconRegistry
