import type { TenantThemePreset, ThemePalette } from '../types/tenant'

export type ThemePresetDef = {
  name: TenantThemePreset
  label: string
  palette: ThemePalette
}

export const THEME_PRESETS: ThemePresetDef[] = [
  {
    name: 'fresh',
    label: 'Fresh',
    palette: {
      primary: '#ff6b35',
      bg: '#ffffff',
      surface: '#f5f5f5',
      text: '#111111',
      textSecondary: '#666666',
      textMuted: '#999999',
      border: '#e0e0e0',
    },
  },
  {
    name: 'dark',
    label: 'Dark',
    palette: {
      primary: '#ff6b35',
      bg: '#2d1208',
      surface: '#3d1a0e',
      text: '#f5ede8',
      textSecondary: '#c4a090',
      textMuted: '#8a6055',
      border: '#4d2418',
    },
  },
  {
    name: 'forest',
    label: 'Forest',
    palette: {
      primary: '#4ade80',
      bg: '#0f1f14',
      surface: '#172a1c',
      text: '#e8f5ec',
      textSecondary: '#8db89a',
      textMuted: '#5a7d65',
      border: '#243d2b',
    },
  },
  {
    name: 'sakura',
    label: 'Sakura',
    palette: {
      primary: '#e91e8c',
      bg: '#fff5f9',
      surface: '#ffeef5',
      text: '#2d0a1a',
      textSecondary: '#7a3a57',
      textMuted: '#b07090',
      border: '#f5d0e3',
    },
  },
  {
    name: 'slate',
    label: 'Slate',
    palette: {
      primary: '#6366f1',
      bg: '#0f172a',
      surface: '#1e293b',
      text: '#f1f5f9',
      textSecondary: '#94a3b8',
      textMuted: '#64748b',
      border: '#334155',
    },
  },
  {
    name: 'cream',
    label: 'Cream',
    palette: {
      primary: '#c2783a',
      bg: '#fdf8f0',
      surface: '#f5ede0',
      text: '#2c1a08',
      textSecondary: '#7a5535',
      textMuted: '#b08060',
      border: '#e8d5bc',
    },
  },
  {
    name: 'neon',
    label: 'Neon',
    palette: {
      primary: '#ff2d78',
      bg: '#08000f',
      surface: '#12001f',
      text: '#ffffff',
      textSecondary: '#cc88ff',
      textMuted: '#7744aa',
      border: '#2a0044',
    },
  },
  {
    name: 'sunset',
    label: 'Sunset',
    palette: {
      primary: '#f97316',
      bg: '#1a0a2e',
      surface: '#2d1045',
      text: '#fde8d8',
      textSecondary: '#c4909a',
      textMuted: '#8a5060',
      border: '#4a1a50',
    },
  },
  {
    name: 'ocean',
    label: 'Ocean',
    palette: {
      primary: '#06b6d4',
      bg: '#040d1a',
      surface: '#0a1a2e',
      text: '#e0f4ff',
      textSecondary: '#7ab8d4',
      textMuted: '#4a7a94',
      border: '#0f2a3d',
    },
  },
  {
    name: 'lemon',
    label: 'Lemon',
    palette: {
      primary: '#b8900a',
      bg: '#fffff0',
      surface: '#fefce8',
      text: '#1a1400',
      textSecondary: '#6b5800',
      textMuted: '#a07800',
      border: '#f5d960',
    },
  },
  {
    name: 'ember',
    label: 'Ember',
    palette: {
      primary: '#E8622A',
      bg: '#1A1410',
      surface: '#261D17',
      text: '#F5EBE0',
      textSecondary: '#C9A882',
      textMuted: '#7A6152',
      border: '#3D2E24',
    },
  },
  {
    name: 'garden',
    label: 'Garden',
    palette: {
      primary: '#3E8C4B',
      bg: '#F7F4EF',
      surface: '#FFFFFF',
      text: '#1E2B1A',
      textSecondary: '#4A5E44',
      textMuted: '#9AAB8E',
      border: '#DDE5D8',
    },
  },
  {
    name: 'midnight',
    label: 'Midnight',
    palette: {
      primary: '#E8AC34',
      bg: '#0E0F14',
      surface: '#16171F',
      text: '#EEEDF2',
      textSecondary: '#9E9DAD',
      textMuted: '#52505E',
      border: '#24242F',
    },
  },
  {
    name: 'berry',
    label: 'Berry',
    palette: {
      primary: '#a02844',
      bg: '#FDF5F7',
      surface: '#FFFFFF',
      text: '#2A1520',
      textSecondary: '#6B3A4E',
      textMuted: '#B8879A',
      border: '#F0DCE3',
    },
  },
  {
    name: 'fiesta',
    label: 'Fiesta',
    palette: {
      primary: '#E84545',
      bg: '#FAF7F2',
      surface: '#FFFFFF',
      text: '#1C1814',
      textSecondary: '#5C5248',
      textMuted: '#A89E94',
      border: '#EAE4DC',
    },
  },

  // ─── light ────────────────────────────────────────────────────────────────

  {
    name: 'breeze',
    label: 'Breeze',
    palette: {
      primary: '#2d60be',
      bg: '#f5f9ff',
      surface: '#edf3fe',
      text: '#0a1628',
      textSecondary: '#3d5a96',
      textMuted: '#7a9acc',
      border: '#c0d8f5',
    },
  },
  {
    name: 'lavender',
    label: 'Lavender',
    palette: {
      primary: '#6a48c0',
      bg: '#faf5ff',
      surface: '#f3ebfe',
      text: '#1a0a30',
      textSecondary: '#5540a0',
      textMuted: '#9a7cc8',
      border: '#ddd0f8',
    },
  },
  {
    name: 'matcha',
    label: 'Matcha',
    palette: {
      primary: '#3d7a4a',
      bg: '#f4faf5',
      surface: '#e8f5ea',
      text: '#0e1e12',
      textSecondary: '#2d5838',
      textMuted: '#7aaa84',
      border: '#c4e2ca',
    },
  },
  {
    name: 'latte',
    label: 'Latte',
    palette: {
      primary: '#7c5c3e',
      bg: '#f7f5f2',
      surface: '#efecea',
      text: '#1a1814',
      textSecondary: '#5a5040',
      textMuted: '#aaa090',
      border: '#dcdad4',
    },
  },
  {
    name: 'frost',
    label: 'Frost',
    palette: {
      primary: '#2a5494',
      bg: '#f0f4f8',
      surface: '#e4ecf5',
      text: '#0c1828',
      textSecondary: '#3060a0',
      textMuted: '#6888b8',
      border: '#b8cce8',
    },
  },
  {
    name: 'peach',
    label: 'Peach',
    palette: {
      primary: '#c44428',
      bg: '#fff7f4',
      surface: '#ffeee8',
      text: '#2a0c04',
      textSecondary: '#8a3020',
      textMuted: '#c48070',
      border: '#f8cfc0',
    },
  },

  // ─── dark ─────────────────────────────────────────────────────────────────

  {
    name: 'graphite',
    label: 'Graphite',
    palette: {
      primary: '#40aec8',
      bg: '#1a1c1e',
      surface: '#242628',
      text: '#f0f2f4',
      textSecondary: '#9098a0',
      textMuted: '#5a6068',
      border: '#3a3e42',
    },
  },
  {
    name: 'obsidian',
    label: 'Obsidian',
    palette: {
      primary: '#a78bfa',
      bg: '#0c0c14',
      surface: '#14141f',
      text: '#f0eeff',
      textSecondary: '#8880cc',
      textMuted: '#4a4880',
      border: '#22203a',
    },
  },
  {
    name: 'velvet',
    label: 'Velvet',
    palette: {
      primary: '#f43f5e',
      bg: '#160810',
      surface: '#22101a',
      text: '#fce8f0',
      textSecondary: '#b87090',
      textMuted: '#6a3050',
      border: '#3a1028',
    },
  },
  {
    name: 'matrix',
    label: 'Matrix',
    palette: {
      primary: '#15c544',
      bg: '#030d08',
      surface: '#081a10',
      text: '#e0ffe8',
      textSecondary: '#40a058',
      textMuted: '#256034',
      border: '#0c2818',
    },
  },
  {
    name: 'dusk',
    label: 'Dusk',
    palette: {
      primary: '#fb923c',
      bg: '#100820',
      surface: '#1a1030',
      text: '#f5e8ff',
      textSecondary: '#b080d0',
      textMuted: '#6040a0',
      border: '#2a1848',
    },
  },
  {
    name: 'nordic',
    label: 'Nordic',
    palette: {
      primary: '#506cc8',
      bg: '#2e3440',
      surface: '#3b4252',
      text: '#eceff4',
      textSecondary: '#9aa8c0',
      textMuted: '#607088',
      border: '#4c566a',
    },
  },

  // ─── colorful / playful ───────────────────────────────────────────────────

  {
    name: 'candy',
    label: 'Candy',
    palette: {
      primary: '#ff1493',
      bg: '#ffffff',
      surface: '#fff0f8',
      text: '#1e0010',
      textSecondary: '#880040',
      textMuted: '#cc60a0',
      border: '#ffc8e8',
    },
  },
  {
    name: 'sunshine',
    label: 'Sunshine',
    palette: {
      primary: '#ff8c00',
      bg: '#fffcf0',
      surface: '#fff5d0',
      text: '#1a0f00',
      textSecondary: '#8a5200',
      textMuted: '#c09040',
      border: '#ffe08a',
    },
  },
  {
    name: 'bubble',
    label: 'Bubble',
    palette: {
      primary: '#e81fba',
      bg: '#f0f8ff',
      surface: '#ddeeff',
      text: '#001428',
      textSecondary: '#1a5080',
      textMuted: '#6090c0',
      border: '#b0d4f0',
    },
  },
  {
    name: 'tropical',
    label: 'Tropical',
    palette: {
      primary: '#ff4500',
      bg: '#e8fff8',
      surface: '#c8f8ec',
      text: '#001a12',
      textSecondary: '#006040',
      textMuted: '#30a080',
      border: '#80e8cc',
    },
  },
  {
    name: 'jellybean',
    label: 'Jellybean',
    palette: {
      primary: '#7c00f5',
      bg: '#f7ffe8',
      surface: '#eaffc0',
      text: '#0a1800',
      textSecondary: '#2a5000',
      textMuted: '#608030',
      border: '#ccf080',
    },
  },
  {
    name: 'melon',
    label: 'Melon',
    palette: {
      primary: '#00c050',
      bg: '#fff5ee',
      surface: '#ffe8d4',
      text: '#2a0800',
      textSecondary: '#8a4020',
      textMuted: '#c08060',
      border: '#f8c8a0',
    },
  },

  // ─── light +10 ────────────────────────────────────────────────────────────

  {
    name: 'chalk',
    label: 'Chalk',
    palette: {
      primary: '#2c2c2c',
      bg: '#ffffff',
      surface: '#f6f6f5',
      text: '#111111',
      textSecondary: '#555555',
      textMuted: '#999999',
      border: '#e2e2e0',
    },
  },
  {
    name: 'sage',
    label: 'Sage',
    palette: {
      primary: '#4e7055',
      bg: '#f3f6f0',
      surface: '#e8ede4',
      text: '#182018',
      textSecondary: '#3e5840',
      textMuted: '#809a82',
      border: '#ccd8c8',
    },
  },
  {
    name: 'teal',
    label: 'Teal',
    palette: {
      primary: '#0a8888',
      bg: '#f0fffe',
      surface: '#dff8f5',
      text: '#001e1c',
      textSecondary: '#0a5858',
      textMuted: '#50a0a0',
      border: '#a0e0dc',
    },
  },
  {
    name: 'plum',
    label: 'Plum',
    palette: {
      primary: '#6e2872',
      bg: '#fcf4fc',
      surface: '#f5e5f5',
      text: '#1e081e',
      textSecondary: '#5a2860',
      textMuted: '#a870a8',
      border: '#e4c8e4',
    },
  },
  {
    name: 'sky',
    label: 'Sky',
    palette: {
      primary: '#1890d0',
      bg: '#f5fcff',
      surface: '#e5f4ff',
      text: '#041828',
      textSecondary: '#0e6090',
      textMuted: '#6098c8',
      border: '#b4dcf5',
    },
  },
  {
    name: 'moss',
    label: 'Moss',
    palette: {
      primary: '#4a5e20',
      bg: '#f8f8f0',
      surface: '#eff0e2',
      text: '#181c08',
      textSecondary: '#3c4818',
      textMuted: '#888a60',
      border: '#d8dcc0',
    },
  },
  {
    name: 'blush',
    label: 'Blush',
    palette: {
      primary: '#b06878',
      bg: '#fff8f9',
      surface: '#feeef0',
      text: '#200c10',
      textSecondary: '#6a3848',
      textMuted: '#c08898',
      border: '#f0d4d8',
    },
  },
  {
    name: 'indigo',
    label: 'Indigo',
    palette: {
      primary: '#3a3898',
      bg: '#f8f8ff',
      surface: '#efeffe',
      text: '#0c0c28',
      textSecondary: '#404080',
      textMuted: '#8888c0',
      border: '#d8d8f8',
    },
  },
  {
    name: 'copper',
    label: 'Copper',
    palette: {
      primary: '#b05c20',
      bg: '#fef8f4',
      surface: '#fdeee4',
      text: '#221008',
      textSecondary: '#703820',
      textMuted: '#c08860',
      border: '#f0d4b8',
    },
  },
  {
    name: 'spruce',
    label: 'Spruce',
    palette: {
      primary: '#285a40',
      bg: '#f4f8f6',
      surface: '#e4f0ea',
      text: '#0c2018',
      textSecondary: '#246040',
      textMuted: '#6aaa80',
      border: '#c0dcc8',
    },
  },

  // ─── dark +10 ─────────────────────────────────────────────────────────────

  {
    name: 'espresso',
    label: 'Espresso',
    palette: {
      primary: '#c8a070',
      bg: '#140c08',
      surface: '#201410',
      text: '#f5ede0',
      textSecondary: '#c0a880',
      textMuted: '#806040',
      border: '#302018',
    },
  },
  {
    name: 'navy',
    label: 'Navy',
    palette: {
      primary: '#90b8d8',
      bg: '#06101e',
      surface: '#0c1a2e',
      text: '#e8f0f8',
      textSecondary: '#7090b8',
      textMuted: '#405880',
      border: '#142038',
    },
  },
  {
    name: 'burgundy',
    label: 'Burgundy',
    palette: {
      primary: '#d4a848',
      bg: '#180c0c',
      surface: '#241214',
      text: '#f8e8e0',
      textSecondary: '#b87870',
      textMuted: '#684848',
      border: '#3c1818',
    },
  },
  {
    name: 'abyss',
    label: 'Abyss',
    palette: {
      primary: '#40a8a0',
      bg: '#030c10',
      surface: '#081418',
      text: '#d8f4f0',
      textSecondary: '#508888',
      textMuted: '#285858',
      border: '#0c2028',
    },
  },
  {
    name: 'pitch',
    label: 'Pitch',
    palette: {
      primary: '#e04040',
      bg: '#0c0c0c',
      surface: '#161616',
      text: '#f4f4f4',
      textSecondary: '#909090',
      textMuted: '#505050',
      border: '#282828',
    },
  },
  {
    name: 'storm',
    label: 'Storm',
    palette: {
      primary: '#90a8cc',
      bg: '#0e121a',
      surface: '#161c28',
      text: '#e8ecf4',
      textSecondary: '#7888a8',
      textMuted: '#485868',
      border: '#242c3c',
    },
  },
  {
    name: 'aubergine',
    label: 'Aubergine',
    palette: {
      primary: '#c060a0',
      bg: '#100814',
      surface: '#180c1e',
      text: '#f5e8ff',
      textSecondary: '#9860b8',
      textMuted: '#504070',
      border: '#28103a',
    },
  },
  {
    name: 'forge',
    label: 'Forge',
    palette: {
      primary: '#d87030',
      bg: '#141210',
      surface: '#201e1a',
      text: '#f2ede8',
      textSecondary: '#a09888',
      textMuted: '#5c5850',
      border: '#302c28',
    },
  },
  {
    name: 'pine',
    label: 'Pine',
    palette: {
      primary: '#388060',
      bg: '#060e08',
      surface: '#0c1810',
      text: '#d8f0e0',
      textSecondary: '#508870',
      textMuted: '#285840',
      border: '#102418',
    },
  },
  {
    name: 'night',
    label: 'Night',
    palette: {
      primary: '#b8a8e8',
      bg: '#08080e',
      surface: '#10101a',
      text: '#f0eeff',
      textSecondary: '#8880c0',
      textMuted: '#484868',
      border: '#1c1c2c',
    },
  },

  // ─── colorful +10 ─────────────────────────────────────────────────────────

  {
    name: 'neon-mint',
    label: 'Neon Mint',
    palette: {
      primary: '#00d878',
      bg: '#f0fff8',
      surface: '#d8ffe8',
      text: '#001e0c',
      textSecondary: '#006040',
      textMuted: '#30a060',
      border: '#80f0c0',
    },
  },
  {
    name: 'lollipop',
    label: 'Lollipop',
    palette: {
      primary: '#ff2828',
      bg: '#fff5f8',
      surface: '#ffe8f0',
      text: '#1e0010',
      textSecondary: '#800030',
      textMuted: '#c06080',
      border: '#ffc0d8',
    },
  },
  {
    name: 'popsicle',
    label: 'Popsicle',
    palette: {
      primary: '#6000d0',
      bg: '#fff8e0',
      surface: '#fff0b0',
      text: '#1a1000',
      textSecondary: '#4a3800',
      textMuted: '#9a8800',
      border: '#f0d840',
    },
  },
  {
    name: 'bubblegum',
    label: 'Bubblegum',
    palette: {
      primary: '#00c0d8',
      bg: '#fff0fc',
      surface: '#ffe0f8',
      text: '#1e0018',
      textSecondary: '#801060',
      textMuted: '#c060a0',
      border: '#f8b8f0',
    },
  },
  {
    name: 'mango',
    label: 'Mango',
    palette: {
      primary: '#e0008a',
      bg: '#fffae8',
      surface: '#fff2c0',
      text: '#1e1400',
      textSecondary: '#806000',
      textMuted: '#c09800',
      border: '#f8e060',
    },
  },
  {
    name: 'cotton',
    label: 'Cotton',
    palette: {
      primary: '#0090f0',
      bg: '#ffffff',
      surface: '#e8f8ff',
      text: '#00142a',
      textSecondary: '#0050a0',
      textMuted: '#6098d0',
      border: '#b0dcff',
    },
  },
  {
    name: 'gummy',
    label: 'Gummy',
    palette: {
      primary: '#ff2020',
      bg: '#f0ffe0',
      surface: '#d8ff90',
      text: '#0a1800',
      textSecondary: '#306000',
      textMuted: '#6a9840',
      border: '#b8f060',
    },
  },
  {
    name: 'festival',
    label: 'Festival',
    palette: {
      primary: '#0050d0',
      bg: '#fff8e0',
      surface: '#fff0b0',
      text: '#1a1400',
      textSecondary: '#504000',
      textMuted: '#a08800',
      border: '#f0e040',
    },
  },
  {
    name: 'dragonfly',
    label: 'Dragonfly',
    palette: {
      primary: '#78e800',
      bg: '#f4f0ff',
      surface: '#eae0ff',
      text: '#140a20',
      textSecondary: '#4a2880',
      textMuted: '#9068c8',
      border: '#d8c0f8',
    },
  },
  {
    name: 'sorbet',
    label: 'Sorbet',
    palette: {
      primary: '#00c8b0',
      bg: '#fff5f0',
      surface: '#ffe8dc',
      text: '#1e0800',
      textSecondary: '#803020',
      textMuted: '#c08070',
      border: '#f8c8b0',
    },
  },
]

export const getPresetPalette = (name: string): ThemePalette | null =>
  THEME_PRESETS.find(p => p.name === name)?.palette ?? null

export const paletteToCssVars = (p: ThemePalette): Record<string, string> => ({
  '--primary': p.primary,
  '--color-bg': p.bg,
  '--color-surface': p.surface,
  '--color-text': p.text,
  '--color-text-secondary': p.textSecondary,
  '--color-text-muted': p.textMuted,
  '--color-border': p.border,
})
