-- Pending auth sessions for bot-based Telegram login flow.
-- Nonce is generated by the storefront on init, stored here, resolved when user
-- presses Start in the bot. Poll endpoint reads completed records and issues a session cookie.

CREATE TABLE pending_telegram_auths (
  nonce          text        PRIMARY KEY,
  tenant_id      uuid        NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  telegram_id    text,
  telegram_data  jsonb,
  phone          text,
  expires_at     timestamptz NOT NULL,
  completed_at   timestamptz
);

-- Used by the webhook to find the pending auth by telegram_id when user responds with contact/skip
CREATE INDEX idx_pending_tg_auth_by_tgid
  ON pending_telegram_auths(telegram_id)
  WHERE telegram_id IS NOT NULL AND completed_at IS NULL;

ALTER TABLE pending_telegram_auths ENABLE ROW LEVEL SECURITY;
CREATE POLICY "pending_telegram_auths: service role only"
  ON pending_telegram_auths FOR ALL USING (auth.role() = 'service_role');

-- Cleanup expired/completed records daily
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM cron.job WHERE jobname = 'pending_telegram_auths_cleanup') THEN
    PERFORM cron.unschedule('pending_telegram_auths_cleanup');
  END IF;
END $$;

SELECT cron.schedule(
  'pending_telegram_auths_cleanup',
  '23 3 * * *',
  $$DELETE FROM pending_telegram_auths WHERE expires_at < now() - interval '1 hour'$$
);
