import type { GlobalThemeOverrides } from 'naive-ui'
import { COLORS } from '../constants/colors'

const naiveUiThemeOverrides: GlobalThemeOverrides = {
  common: {
    fontFamily: 'Inter, sans-serif',
    fontWeightStrong: '700',
    borderRadius: '12px',
    fontSizeTiny: '14px',
    fontSizeSmall: '14px',
    fontSizeMedium: '14px',
    fontSizeLarge: '14px',
    heightTiny: '24px',
    heightSmall: '32px',
    heightMedium: '40px',
    heightLarge: '48px',
    baseColor: COLORS.WHITE,
    primaryColor: COLORS.PRIMARY,
    primaryColorHover: COLORS.BLUE_400,
    primaryColorPressed: COLORS.PRIMARY,
    successColor: COLORS.SUCCESS,
    errorColor: COLORS.RED_500,
    errorColorHover: COLORS.RED_600,
    errorColorPressed: COLORS.RED_700,
    borderColor: COLORS.GREY_200,
    fontWeight: '700',
    textColorBase: COLORS.TITLE,
    closeIconColor: COLORS.GREY_100,
  },
  Button: {
    rippleDuration: '0',
    borderRadiusTiny: '6px',
    borderRadiusSmall: '8px',
    borderRadiusMedium: '8px',
    borderRadiusLarge: '12px',
    paddingTiny: '0 20px',
    paddingSmall: '0 20px',
    paddingMedium: '0 20px',
    paddingLarge: '0 20px',
    iconMarginTiny: '8px',
    iconMarginSmall: '8px',
    iconMarginMedium: '8px',
    iconMarginLarge: '8px',
    iconSizeTiny: '16px',
    iconSizeSmall: '16px',
    iconSizeMedium: '24px',
    iconSizeLarge: '24px',
  },
  Input: {
    fontWeight: '400',
    // Минимум 16px чтобы iOS Safari не зумил страницу при фокусе
    fontSizeTiny: '16px',
    fontSizeSmall: '16px',
    fontSizeMedium: '16px',
    fontSizeLarge: '16px',
    placeholderColor: COLORS.GREY_500,
    boxShadowFocus: 'none',
    boxShadowFocusWarning: 'none',
    boxShadowFocusError: 'none',
    paddingTiny: '0 8px',
    paddingSmall: '0 12px',
    paddingMedium: '0 16px',
    paddingLarge: '0 16px 0 24px',
    textColorDisabled: COLORS.GREY_300,
    groupLabelBorder: `2px solid ${COLORS.GREY_200}`,
    border: `2px solid ${COLORS.GREY_200}`,
    borderHover: `2px solid ${COLORS.BLUE_400}`,
    borderDisabled: `2px solid ${COLORS.GREY_200}`,
    borderFocus: `2px solid ${COLORS.BLUE_400}`,
    borderWarning: `2px solid ${COLORS.WARNING}`,
    borderHoverWarning: `2px solid ${COLORS.YELLOW_400}`,
    borderFocusWarning: `2px solid ${COLORS.YELLOW_400}`,
    borderError: `2px solid ${COLORS.ERROR}`,
    borderHoverError: `2px solid ${COLORS.RED_500}`,
    borderFocusError: `2px solid ${COLORS.RED_500}`,
  },
  Collapse: {
    dividerColor: COLORS.GREY_200,
  },
  Checkbox: {
    sizeSmall: '16px',
    sizeMedium: '20px',
    sizeLarge: '24px',
    fontSizeSmall: '12px',
    fontSizeMedium: '14px',
    fontSizeLarge: '16px',
    borderRadius: '5px',
    checkMarkColorDisabled: COLORS.GREY_200,
    checkMarkColorDisabledChecked: COLORS.WHITE,
    colorDisabledChecked: COLORS.GREY_200,
    border: `2px solid ${COLORS.PRIMARY}`,
    borderDisabled: `2px solid ${COLORS.GREY_200}`,
    borderDisabledChecked: `2px solid ${COLORS.GREY_200}`,
    borderChecked: `2px solid ${COLORS.PRIMARY}`,
    borderFocus: `2px solid ${COLORS.PRIMARY}`,
    textColor: COLORS.TITLE,
    textColorDisabled: COLORS.GREY_300,
    boxShadowFocus: 'none',
  },
  Radio: {
    radioSizeSmall: '16px',
    radioSizeMedium: '20px',
    radioSizeLarge: '24px',
    fontSizeSmall: '12px',
    fontSizeMedium: '14px',
    fontSizeLarge: '16px',
    boxShadow: `inset 0 0 0 2px ${COLORS.PRIMARY}`,
    boxShadowActive: `inset 0 0 0 2px ${COLORS.PRIMARY}`,
    boxShadowFocus: `inset 0 0 0 2px ${COLORS.PRIMARY}`,
    boxShadowHover: `inset 0 0 0 2px ${COLORS.BLUE_400}`,
    boxShadowDisabled: `inset 0 0 0 2px ${COLORS.GREY_200}`,
    textColorDisabled: COLORS.GREY_300,
    textColor: COLORS.TITLE,
  },
  Select: {
    menuBoxShadow: 'none',
    border: `2px solid ${COLORS.GREY_200}`,
    borderHover: `2px solid ${COLORS.BLUE_400}`,
    borderActive: `2px solid ${COLORS.BLUE_400}`,
    borderFocus: `2px solid ${COLORS.BLUE_400}`,
    peers: {
      InternalSelectMenu: {
        optionColorPending: COLORS.BLUE_50,
        optionColorActive: COLORS.BLUE_50,
        optionColorActivePending: COLORS.BLUE_50,
        optionHeightTiny: '24px',
        optionHeightSmall: '32px',
        optionHeightMedium: '40px',
        optionHeightLarge: '48px',
      },
    },
  },
  DatePicker: {
    calendarDividerColor: COLORS.GREY_200,
    calendarTitleColorHover: COLORS.BLUE_50,
    itemColorHover: COLORS.BLUE_50,
    itemColorActive: COLORS.PRIMARY,
    itemColorActiveHover: COLORS.BLUE_400,
    itemBorderRadius: '50px',
    arrowSize: '24px',
  },
  Pagination: {
    buttonColor: 'transparent',
    itemColor: 'transparent',
    itemColorActive: COLORS.BLUE_50,
    buttonBorder: 'none',
    itemBorderActive: 'none',
    itemColorHover: COLORS.BLUE_50,
    itemColorPressed: COLORS.BLUE_50,
    itemColorActiveHover: COLORS.BLUE_50,
    pageSlot: 7,
    itemBorderRadius: '8px',
    itemFontSizeTiny: '12px',
    itemFontSizeSmall: '14px',
    itemFontSizeMedium: '16px',
    itemFontSizeLarge: '16px',
  },
  Menu: {
    itemHeight: '38px',
    itemTextColor: COLORS.GREY_900,
    itemTextColorHover: COLORS.GREY_900,
    itemColorHover: 'transparent',
    itemColorActive: 'transparent',
    itemColorActiveHover: 'transparent',
    itemTextColorActive: COLORS.TITLE,
    itemTextColorActiveHover: COLORS.TITLE,
    itemTextColorChildActive: COLORS.TITLE,
    itemTextColorChildActiveHover: COLORS.TITLE,
    itemIconColorActive: COLORS.TITLE,
    itemIconColorActiveHover: COLORS.TITLE,
    itemIconColorChildActive: COLORS.TITLE,
    itemIconColorChildActiveHover: COLORS.TITLE,
    arrowColorActive: COLORS.TITLE,
    arrowColorActiveHover: COLORS.TITLE,
    arrowColorChildActive: COLORS.TITLE,
    arrowColorChildActiveHover: COLORS.TITLE,
  },
  Alert: {
    colorInfo: COLORS.BLUE_50,
    colorSuccess: COLORS.GREEN_100,
    colorWarning: COLORS.YELLOW_100,
    colorError: COLORS.RED_100,
  },
}

export default naiveUiThemeOverrides
